// Knowledge/frontend/packages/WebSocket/webSocket-vue-demo/src/components/ChatRoom.vue
<template>
  <div class="chat-room">
    <ChatHeader 
      :user="user"
      :connection-status="connectionStatus"
      :is-connected="webSocketStore.isConnected"
      @disconnect="$emit('logout')"
    />
    
    <div class="chat-body">
      <div class="chat-main">
        <MessageList 
          :messages="chatStore.messages"
          :current-user="user"
        />
        
        <MessageInput 
          :disabled="!webSocketStore.isConnected"
          :placeholder="inputPlaceholder"
          @send-message="handleSendMessage"
          @typing="handleTyping"
        />
      </div>
      
      <ChatSidebar 
        :users="chatStore.users"
        :current-user="user"
        :server-url="serverUrl"
        :connection-info="webSocketStore.connectionInfo"
        @clear-messages="handleClearMessages"
        @test-connection="handleTestConnection"
      />
    </div>
    
    <NotificationContainer 
      :notifications="chatStore.notifications"
      @remove="handleRemoveNotification"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useWebSocketChat } from '@/composables/useWebSocketChat'
import ChatHeader from './ChatHeader.vue'
import MessageList from './MessageList.vue'
import MessageInput from './MessageInput.vue'
import ChatSidebar from './ChatSidebar.vue'
import NotificationContainer from './NotificationContainer.vue'
import type { ChatRoomProps } from '@/types'

// Props
defineProps<ChatRoomProps>()

// Emits
defineEmits<{
  logout: []
}>()

// 使用组合式函数
const { 
  webSocketStore, 
  chatStore, 
  sendMessage, 
  sendTypingStatus, 
  clearMessages, 
  testConnection 
} = useWebSocketChat()

// 计算属性
const connectionStatus = computed<string>(() => {
  if (webSocketStore.isConnecting) return '连接中...'
  if (webSocketStore.isConnected) return '已连接'
  return '未连接'
})

const inputPlaceholder = computed<string>(() => {
  if (!webSocketStore.isConnected) return '连接断开，无法发送消息...'
  if (chatStore.hasTypingUsers) {
    const users = chatStore.typingUsers.join(', ')
    return `${users} 正在输入...`
  }
  return '输入消息...'
})

// 事件处理
const handleSendMessage = (content: string): void => {
  sendMessage(content)
}

const handleTyping = (isTyping: boolean): void => {
  sendTypingStatus(isTyping)
}

const handleClearMessages = (): void => {
  clearMessages()
}

const handleTestConnection = (): void => {
  testConnection()
}

const handleRemoveNotification = (id: string): void => {
  chatStore.removeNotification(id)
}
</script>

<style scoped>
.chat-room {
  display: flex;
  flex-direction: column;
  height: 100%;
  position: relative;
}

.chat-body {
  display: flex;
  flex: 1;
  overflow: hidden;
}

.chat-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

@media (max-width: 768px) {
  .chat-body {
    flex-direction: column;
  }
}
</style>

// demos/websocket-react/src/components/ChatRoom.tsx
import React, { useCallback } from 'react';
import { observer } from 'mobx-react-lite';
import styled from 'styled-components';
import { useStores } from '@/stores/RootStore';
import type { ChatRoomProps } from '@/types';
import ChatHeader from './ChatHeader';
import ChatSidebar from './ChatSidebar';
import MessageList from './MessageList';
import MessageInput from './MessageInput';
import NotificationContainer from './NotificationContainer';

const ChatContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  background: #313338;
`;

const ChatMain = styled.div`
  flex: 1;
  display: flex;
  min-height: 0;
`;

const ChatArea = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
  min-width: 0;
`;

const ChatRoom: React.FC<ChatRoomProps> = observer(({ user, serverUrl, onLogout }) => {
  const {
    chatStore,
    webSocketStore,
    sendMessage,
    sendTyping,
    testConnection,
    clearMessages,
    connectionStatusText
  } = useStores();

  const handleLoadMore = useCallback((): void => {
    chatStore.loadHistory();
  }, [chatStore]);

  const handleSendMessage = useCallback((content: string): void => {
    if (!content.trim()) return;
    sendMessage(content);
  }, [sendMessage]);

  const handleTypingChange = useCallback((isTyping: boolean): void => {
    chatStore.setTyping(isTyping);
    sendTyping(isTyping);
  }, [chatStore, sendTyping]);

  const handleDisconnect = useCallback((): void => {
    onLogout();
  }, [onLogout]);

  const handleTestConnection = useCallback((): void => {
    testConnection();
  }, [testConnection]);

  const handleClearMessages = useCallback((): void => {
    clearMessages();
  }, [clearMessages]);

  const handleRemoveNotification = useCallback((id: string): void => {
    chatStore.removeNotification(id);
  }, [chatStore]);

  const handleRetryMessage = useCallback((messageId: string): void => {
    // TODO: 实现消息重试逻辑
    chatStore.showNotification('消息重试功能开发中', 'info');
  }, [chatStore]);

  return (
    <ChatContainer>
      <ChatHeader
        user={user}
        connectionStatus={connectionStatusText}
        isConnected={webSocketStore.isConnected}
        onDisconnect={handleDisconnect}
      />

      <ChatMain>
        <ChatSidebar
          users={chatStore.users}
          currentUser={user}
          serverUrl={serverUrl}
          connectionInfo={webSocketStore.getConnectionInfo()}
          onClearMessages={handleClearMessages}
          onTestConnection={handleTestConnection}
        />

        <ChatArea>
          <MessageList
            messages={chatStore.messages}
            currentUser={user}
            onLoadMore={handleLoadMore}
            onRetry={handleRetryMessage}
            isLoadingHistory={chatStore.isLoadingHistory}
            hasMoreHistory={chatStore.hasMoreHistory}
          />

          <MessageInput
            onSendMessage={handleSendMessage}
            onTypingChange={handleTypingChange}
            disabled={!webSocketStore.isConnected}
            placeholder={
              webSocketStore.isConnected
                ? '输入消息...'
                : webSocketStore.isConnecting
                  ? '连接中...'
                  : '未连接'
            }
            maxLength={500}
          />
        </ChatArea>
      </ChatMain>

      <NotificationContainer
        notifications={chatStore.notifications}
        onRemove={handleRemoveNotification}
      />
    </ChatContainer>
  );
});

ChatRoom.displayName = 'ChatRoom';

export default ChatRoom;
