// demos/websocket-vue/src/components/NotificationContainer.vue
<template>
  <div class="notification-container">
    <TransitionGroup name="notification" tag="div" class="notification-list">
      <div
        v-for="notification in notifications"
        :key="notification.id"
        class="notification"
        :class="getNotificationClass(notification)"
      >
        <div class="notification-icon">
          {{ getNotificationIcon(notification.type) }}
        </div>
        
        <div class="notification-content">
          <div class="notification-message">
            {{ notification.message }}
          </div>
          <div class="notification-time">
            {{ formatTime(notification.timestamp) }}
          </div>
        </div>
        
        <button 
          class="notification-close"
          @click="$emit('remove', notification.id)"
          title="关闭"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      </div>
    </TransitionGroup>
  </div>
</template>

<script setup lang="ts">
import type { Notification, NotificationLevel, NotificationContainerProps } from '@/types'

// Props
defineProps<NotificationContainerProps>()

// Emits
defineEmits<{
  remove: [id: string]
}>()

// 获取通知样式类
const getNotificationClass = (notification: Notification): string[] => {
  return ['notification-item', `notification-${notification.type}`]
}

// 获取通知图标
const getNotificationIcon = (type: NotificationLevel): string => {
  const icons = {
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
  }
  return icons[type] || icons.info
}

// 格式化时间
const formatTime = (timestamp: number): string => {
  const date = new Date(timestamp)
  return date.toLocaleTimeString('zh-CN', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
}
</script>

<style scoped>
.notification-container {
  position: fixed;
  top: 20px;
  right: 20px;
  z-index: 1000;
  pointer-events: none;
}

.notification-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  max-width: 400px;
}

.notification {
  background: white;
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.12);
  border: 1px solid #e5e7eb;
  display: flex;
  align-items: flex-start;
  gap: 0.75rem;
  padding: 1rem;
  min-width: 320px;
  pointer-events: auto;
  backdrop-filter: blur(8px);
  position: relative;
  overflow: hidden;
}

.notification::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 4px;
  transition: background-color 0.2s ease;
}

.notification-success::before {
  background: #10b981;
}

.notification-error::before {
  background: #ef4444;
}

.notification-warning::before {
  background: #f59e0b;
}

.notification-info::before {
  background: #3b82f6;
}

.notification-icon {
  font-size: 1.25rem;
  flex-shrink: 0;
  margin-top: 0.125rem;
}

.notification-content {
  flex: 1;
  min-width: 0;
}

.notification-message {
  font-size: 0.875rem;
  font-weight: 500;
  color: #374151;
  line-height: 1.4;
  margin-bottom: 0.25rem;
  word-break: break-word;
}

.notification-time {
  font-size: 0.75rem;
  color: #6b7280;
}

.notification-close {
  background: none;
  border: none;
  color: #9ca3af;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 4px;
  transition: all 0.2s ease;
  flex-shrink: 0;
  margin-top: -0.25rem;
  margin-right: -0.25rem;
}

.notification-close:hover {
  background: #f3f4f6;
  color: #6b7280;
}

/* 动画效果 */
.notification-enter-active {
  transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
}

.notification-leave-active {
  transition: all 0.3s cubic-bezier(0.7, 0, 0.84, 0);
}

.notification-enter-from {
  transform: translateX(100%);
  opacity: 0;
}

.notification-leave-to {
  transform: translateX(100%);
  opacity: 0;
}

.notification-move {
  transition: transform 0.3s ease;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .notification-container {
    top: 10px;
    right: 10px;
    left: 10px;
  }
  
  .notification-list {
    max-width: none;
  }
  
  .notification {
    min-width: auto;
    padding: 0.875rem;
  }
  
  .notification-message {
    font-size: 0.8125rem;
  }
}

/* 高度适配 */
@media (max-height: 600px) {
  .notification-container {
    top: 10px;
  }
  
  .notification {
    padding: 0.75rem;
  }
}

/* 暗色模式支持 */
@media (prefers-color-scheme: dark) {
  .notification {
    background: rgba(31, 41, 55, 0.95);
    border-color: #374151;
    color: #f9fafb;
  }
  
  .notification-message {
    color: #f9fafb;
  }
  
  .notification-time {
    color: #9ca3af;
  }
  
  .notification-close {
    color: #6b7280;
  }
  
  .notification-close:hover {
    background: #374151;
    color: #9ca3af;
  }
}

/* 减少动画的可访问性设置 */
@media (prefers-reduced-motion: reduce) {
  .notification-enter-active,
  .notification-leave-active,
  .notification-move {
    transition: none;
  }
}
</style>

// demos/websocket-react/src/components/NotificationContainer.tsx
import React, { useCallback } from 'react';
import { observer } from 'mobx-react-lite';
import styled, { keyframes } from 'styled-components';
import type { NotificationContainerProps, Notification, NotificationLevel } from '@/types';
import { Check, AlertCircle, Info, X } from './common/Icons';

const slideIn = keyframes`
  from {
    opacity: 0;
    transform: translateX(100%);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
`;

const Container = styled.div`
  position: fixed;
  top: 16px;
  right: 16px;
  z-index: 2000;
  display: flex;
  flex-direction: column;
  gap: 8px;
  pointer-events: none;

  @media (max-width: 768px) {
    left: 16px;
    right: 16px;
    top: 12px;
  }
`;

const NotificationItem = styled.div<{ $type: NotificationLevel }>`
  background: #2B2D31;
  border-radius: 4px;
  padding: 12px 16px;
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
  border-left: 3px solid ${props => {
    switch (props.$type) {
      case 'success': return '#23A55A';
      case 'error': return '#ED4245';
      case 'warning': return '#F0B232';
      case 'info': return '#5865F2';
      default: return '#5865F2';
    }
  }};
  animation: ${slideIn} 0.2s ease-out;
  max-width: 320px;
  pointer-events: auto;
  position: relative;
  display: flex;
  align-items: flex-start;
  gap: 12px;
  cursor: pointer;
  transition: background 0.1s ease;

  &:hover {
    background: #35373C;
  }

  @media (max-width: 768px) {
    max-width: none;
  }
`;

const IconWrapper = styled.div<{ $type: NotificationLevel }>`
  flex-shrink: 0;
  color: ${props => {
    switch (props.$type) {
      case 'success': return '#23A55A';
      case 'error': return '#ED4245';
      case 'warning': return '#F0B232';
      case 'info': return '#5865F2';
      default: return '#5865F2';
    }
  }};
  display: flex;
`;

const NotificationBody = styled.div`
  flex: 1;
  min-width: 0;
`;

const NotificationMessage = styled.div`
  font-size: 14px;
  font-weight: 500;
  color: #F2F3F5;
  line-height: 1.4;
  word-break: break-word;
`;

const NotificationTime = styled.div`
  font-size: 11px;
  color: #949BA4;
  margin-top: 4px;
`;

const CloseButton = styled.button`
  width: 20px;
  height: 20px;
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #949BA4;
  flex-shrink: 0;
  transition: background 0.1s ease, color 0.1s ease;

  &:hover {
    background: #404249;
    color: #F2F3F5;
  }
`;

const ProgressBar = styled.div<{ $type: NotificationLevel; $duration: number }>`
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: ${props => {
    switch (props.$type) {
      case 'success': return '#23A55A';
      case 'error': return '#ED4245';
      case 'warning': return '#F0B232';
      case 'info': return '#5865F2';
      default: return '#5865F2';
    }
  }};
  border-radius: 0 0 4px 0;
  animation: progressBar ${props => props.$duration}ms linear;
  transform-origin: left;

  @keyframes progressBar {
    from {
      transform: scaleX(1);
    }
    to {
      transform: scaleX(0);
    }
  }
`;

/**
 * 格式化时间
 */
const formatTime = (timestamp: number): string => {
  const now = new Date();
  const notificationTime = new Date(timestamp);
  const diffInSeconds = Math.floor((now.getTime() - notificationTime.getTime()) / 1000);

  if (diffInSeconds < 60) {
    return '刚刚';
  } else if (diffInSeconds < 3600) {
    return `${Math.floor(diffInSeconds / 60)} 分钟前`;
  } else {
    return notificationTime.toLocaleTimeString('zh-CN', {
      hour: '2-digit',
      minute: '2-digit',
    });
  }
};

/**
 * 获取通知图标
 */
const NotificationIcon: React.FC<{ type: NotificationLevel }> = ({ type }) => {
  switch (type) {
    case 'success':
      return <Check size={18} />;
    case 'error':
      return <AlertCircle size={18} />;
    case 'warning':
      return <AlertCircle size={18} />;
    case 'info':
    default:
      return <Info size={18} />;
  }
};

interface NotificationItemComponentProps {
  notification: Notification;
  onRemove: (id: string) => void;
}

const NotificationItemComponent: React.FC<NotificationItemComponentProps> = observer(({
  notification,
  onRemove
}) => {
  const { id, message, type, duration } = notification;

  const handleClick = useCallback((): void => {
    onRemove(id);
  }, [id, onRemove]);

  const handleCloseClick = useCallback((e: React.MouseEvent): void => {
    e.stopPropagation();
    onRemove(id);
  }, [id, onRemove]);

  return (
    <NotificationItem $type={type} onClick={handleClick}>
      <IconWrapper $type={type}>
        <NotificationIcon type={type} />
      </IconWrapper>

      <NotificationBody>
        <NotificationMessage>{message}</NotificationMessage>
        <NotificationTime>
          {formatTime(notification.timestamp || Date.now())}
        </NotificationTime>
      </NotificationBody>

      <CloseButton onClick={handleCloseClick} aria-label="关闭通知">
        <X size={14} />
      </CloseButton>

      {duration && notification.autoClose && (
        <ProgressBar $type={type} $duration={duration} />
      )}
    </NotificationItem>
  );
});

NotificationItemComponent.displayName = 'NotificationItem';

const NotificationContainer: React.FC<NotificationContainerProps> = observer(({
  notifications,
  onRemove
}) => {
  if (!notifications || notifications.length === 0) {
    return null;
  }

  return (
    <Container>
      {notifications.map(notification => (
        <NotificationItemComponent
          key={notification.id}
          notification={notification}
          onRemove={onRemove}
        />
      ))}
    </Container>
  );
});

NotificationContainer.displayName = 'NotificationContainer';

export default NotificationContainer;
