// demos/websocket-vue/src/components/LoginForm.vue
<template>
  <div class="login-container">
    <div class="login-header">
      <h1 class="login-title">WebSocket 聊天室</h1>
      <p class="login-subtitle">基于 Vue 3 + Pinia + TypeScript 构建</p>
    </div>

    <form class="login-form" @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="username" class="form-label">用户名</label>
        <input
          id="username"
          v-model="formData.username"
          type="text"
          class="form-input"
          placeholder="请输入您的用户名"
          :disabled="loading"
          maxlength="20"
          required
        />
      </div>

      <div class="form-group">
        <label for="serverUrl" class="form-label">服务器地址</label>
        <input
          id="serverUrl"
          v-model="formData.serverUrl"
          type="url"
          class="form-input"
          placeholder="ws://localhost:8080"
          :disabled="loading"
          required
        />
      </div>

      <div v-if="error" class="error-message">
        {{ error }}
      </div>

      <button 
        type="submit" 
        class="login-button"
        :disabled="loading || !isFormValid"
      >
        <span v-if="loading" class="loading-spinner"></span>
        {{ loading ? '连接中...' : '加入聊天室' }}
      </button>
    </form>

    <div class="login-footer">
      <div class="features">
        <div class="feature-item">
          <span class="feature-icon">🚀</span>
          <span class="feature-text">实时通信</span>
        </div>
        <div class="feature-item">
          <span class="feature-icon">🔒</span>
          <span class="feature-text">安全连接</span>
        </div>
        <div class="feature-item">
          <span class="feature-icon">⚡</span>
          <span class="feature-text">高性能</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, computed } from 'vue'
import type { LoginFormData, LoginFormProps } from '@/types'

// Props
defineProps<LoginFormProps>()

// Emits
const emit = defineEmits<{
  login: [data: LoginFormData]
}>()

// 表单数据
const formData = reactive<LoginFormData>({
  username: '',
  serverUrl: 'ws://localhost:8080',
})

// 计算属性
const isFormValid = computed<boolean>(() => {
  return formData.username.trim().length >= 2 && 
         formData.serverUrl.trim().length > 0
})

// 处理表单提交
const handleSubmit = (): void => {
  if (isFormValid.value) {
    emit('login', { ...formData })
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100%;
  padding: 2rem;
  background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
}

.login-header {
  text-align: center;
  margin-bottom: 2rem;
}

.login-title {
  font-size: 2.5rem;
  font-weight: 700;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin-bottom: 0.5rem;
}

.login-subtitle {
  color: #64748b;
  font-size: 1rem;
  margin: 0;
}

.login-form {
  width: 100%;
  max-width: 400px;
  padding: 2rem;
  background: white;
  border-radius: 16px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
  margin-bottom: 2rem;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 600;
  color: #374151;
  font-size: 0.875rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.form-input {
  width: 100%;
  padding: 0.875rem 1rem;
  border: 2px solid #e5e7eb;
  border-radius: 12px;
  font-size: 1rem;
  transition: all 0.2s ease;
  background: #fafafa;
}

.form-input:focus {
  outline: none;
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
  background: white;
}

.form-input:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error-message {
  padding: 0.75rem 1rem;
  background: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: 8px;
  color: #dc2626;
  font-size: 0.875rem;
  margin-bottom: 1rem;
}

.login-button {
  width: 100%;
  padding: 1rem;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 12px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
}

.login-button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 8px 20px rgba(102, 126, 234, 0.3);
}

.login-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
  box-shadow: none;
}

.loading-spinner {
  width: 1rem;
  height: 1rem;
  border: 2px solid transparent;
  border-top: 2px solid currentColor;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

.login-footer {
  text-align: center;
}

.features {
  display: flex;
  gap: 2rem;
  justify-content: center;
}

.feature-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.feature-icon {
  font-size: 1.5rem;
}

.feature-text {
  font-size: 0.875rem;
  color: #64748b;
  font-weight: 500;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

@media (max-width: 768px) {
  .login-container {
    padding: 1rem;
  }
  
  .login-title {
    font-size: 2rem;
  }
  
  .login-form {
    padding: 1.5rem;
  }
  
  .features {
    gap: 1rem;
  }
}
</style>

// Knowledge/frontend/packages/WebSocket/webSocket-react-demo/src/components/LoginForm.tsx
import React, { useState } from 'react';
import { observer } from 'mobx-react-lite';
import styled from 'styled-components';
import type { LoginFormProps } from '@/types';

const LoginContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 40px;
`;

const LoginBox = styled.div`
  width: 100%;
  max-width: 400px;
  padding: 40px;
  text-align: center;
  animation: slideUp 0.6s ease-out;

  @keyframes slideUp {
    from {
      opacity: 0;
      transform: translateY(30px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
`;

const Title = styled.h1`
  color: #667eea;
  font-size: 28px;
  font-weight: 700;
  margin-bottom: 10px;
`;

const Subtitle = styled.p`
  color: #666;
  font-size: 16px;
  margin-bottom: 40px;
  line-height: 1.5;
`;

const FormGroup = styled.div`
  margin-bottom: 24px;
  text-align: left;
`;

const Label = styled.label`
  display: block;
  margin-bottom: 8px;
  font-weight: 600;
  color: #333;
  font-size: 14px;
`;

const Input = styled.input<{ hasError?: boolean }>`
  width: 100%;
  padding: 14px 16px;
  border: 2px solid ${props => props.hasError ? '#f44336' : '#e1e8ed'};
  border-radius: 12px;
  font-size: 16px;
  transition: all 0.3s ease;
  background: #fafafa;

  &:focus {
    outline: none;
    border-color: ${props => props.hasError ? '#f44336' : '#667eea'};
    background: white;
    box-shadow: 0 0 0 3px ${props => props.hasError ? 'rgba(244, 67, 54, 0.1)' : 'rgba(102, 126, 234, 0.1)'};
  }

  &::placeholder {
    color: #999;
  }

  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
`;

const ConnectButton = styled.button`
  width: 100%;
  padding: 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 12px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;

  &:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 10px 20px rgba(102, 126, 234, 0.4);
  }

  &:active {
    transform: translateY(0);
  }

  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
    transform: none;
  }

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 100%;
    background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
    transition: left 0.5s;
  }

  &:hover::before {
    left: 100%;
  }
`;

const LoadingSpinner = styled.div`
  width: 20px;
  height: 20px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top: 2px solid white;
  border-radius: 50%;
  animation: spin 1s linear infinite;

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
`;

const ErrorMessage = styled.div`
  background: #fee;
  color: #c53030;
  padding: 12px 16px;
  border-radius: 8px;
  margin-bottom: 20px;
  font-size: 14px;
  border: 1px solid #fed7d7;
  text-align: left;
  animation: fadeIn 0.3s ease-out;

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(-10px); }
    to { opacity: 1; transform: translateY(0); }
  }
`;

const DemoNotice = styled.div`
  margin-top: 30px;
  padding: 20px;
  background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
  border-radius: 12px;
  border-left: 4px solid #667eea;
  text-align: left;

  h4 {
    color: #667eea;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 8px;
    display: flex;
    align-items: center;
    gap: 8px;
  }

  p {
    font-size: 13px;
    color: #666;
    line-height: 1.4;
    margin-bottom: 4px;

    &:last-child {
      margin-bottom: 0;
    }
  }

  .icon {
    font-size: 16px;
  }
`;

const CharacterCount = styled.div<{ isOverLimit: boolean }>`
  font-size: 12px;
  color: ${props => props.isOverLimit ? '#f44336' : '#666'};
  text-align: right;
  margin-top: 4px;
`;

const LoginForm: React.FC<LoginFormProps> = observer(({ onLogin, loading = false, error }) => {
  const [username, setUsername] = useState('');
  const [serverUrl, setServerUrl] = useState('ws://localhost:8080');
  const [localError, setLocalError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const maxUsernameLength = 20;
  const isUsernameOverLimit = username.length > maxUsernameLength;
  const displayError = error || localError;

  const validateWebSocketUrl = (url: string): boolean => {
    try {
      const urlObj = new URL(url);
      return urlObj.protocol === 'ws:' || urlObj.protocol === 'wss:';
    } catch {
      return false;
    }
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    setLocalError('');

    // 前端验证
    if (!username.trim()) {
      setLocalError('请输入用户名');
      return;
    }

    if (username.trim().length < 2) {
      setLocalError('用户名至少需要2个字符');
      return;
    }

    if (isUsernameOverLimit) {
      setLocalError(`用户名不能超过${maxUsernameLength}个字符`);
      return;
    }

    if (!serverUrl.trim()) {
      setLocalError('请输入服务器地址');
      return;
    }

    if (!validateWebSocketUrl(serverUrl.trim())) {
      setLocalError('请输入有效的 WebSocket 地址 (ws:// 或 wss://)');
      return;
    }

    setIsSubmitting(true);
    
    try {
      await onLogin({ username: username.trim(), serverUrl: serverUrl.trim() });
    } catch (err) {
      // 错误已在上层处理
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleUsernameChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const value = e.target.value;
    setUsername(value);
    setLocalError('');
  };

  const handleServerUrlChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    setServerUrl(e.target.value);
    setLocalError('');
  };

  const isDisabled = loading || isSubmitting;

  return (
    <LoginContainer>
      <LoginBox>
        <Title>🚀 WebSocket 聊天室</Title>
        <Subtitle>基于 React + MobX + TypeScript 的实时通信演示</Subtitle>

        <form onSubmit={handleSubmit}>
          {displayError && <ErrorMessage>{displayError}</ErrorMessage>}
          
          <FormGroup>
            <Label htmlFor="username">用户名</Label>
            <Input
              id="username"
              type="text"
              value={username}
              onChange={handleUsernameChange}
              placeholder="请输入您的用户名"
              disabled={isDisabled}
              autoComplete="username"
              autoFocus
              hasError={isUsernameOverLimit}
              maxLength={maxUsernameLength + 5} // 允许稍微超过限制以显示错误
            />
            <CharacterCount isOverLimit={isUsernameOverLimit}>
              {username.length}/{maxUsernameLength}
            </CharacterCount>
          </FormGroup>

          <FormGroup>
            <Label htmlFor="serverUrl">服务器地址</Label>
            <Input
              id="serverUrl"
              type="text"
              value={serverUrl}
              onChange={handleServerUrlChange}
              placeholder="WebSocket服务器地址"
              disabled={isDisabled}
              autoComplete="url"
            />
          </FormGroup>

          <ConnectButton type="submit" disabled={isDisabled || isUsernameOverLimit}>
            {isDisabled && <LoadingSpinner />}
            {isDisabled ? '连接中...' : '连接聊天室'}
          </ConnectButton>
        </form>

        <DemoNotice>
          <h4>
            <span className="icon">💡</span>
            演示说明
          </h4>
          <p>这是一个完整的 React + MobX + TypeScript 演示项目</p>
          <p>包含自动重连、心跳检测、消息队列等功能</p>
          <p>如需完整体验，请启动 WebSocket 服务器</p>
          <p>没有服务器时也可以体验前端界面功能</p>
        </DemoNotice>
      </LoginBox>
    </LoginContainer>
  );
});

LoginForm.displayName = 'LoginForm';

export default LoginForm;
