// Knowledge/frontend/packages/WebSocket/react-demo/src/components/ChatHeader.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import styled from 'styled-components';
import type { ChatHeaderProps } from '@/types';

const HeaderContainer = styled.div`
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);

  @media (max-width: 768px) {
    padding: 16px;
    flex-direction: column;
    gap: 12px;
    text-align: center;
  }
`;

const HeaderLeft = styled.div`
  display: flex;
  flex-direction: column;
  gap: 4px;
`;

const Title = styled.h2`
  font-size: 20px;
  font-weight: 700;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 8px;

  @media (max-width: 768px) {
    font-size: 18px;
    justify-content: center;
  }
`;

const ConnectionStatus = styled.div`
  font-size: 13px;
  opacity: 0.9;
  display: flex;
  align-items: center;
  gap: 6px;

  @media (max-width: 768px) {
    justify-content: center;
  }
`;

interface StatusIndicatorProps {
  isConnected: boolean;
  status: string;
}

const StatusIndicator = styled.span<StatusIndicatorProps>`
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: ${props => {
    if (props.isConnected) return '#4caf50';
    if (props.status.includes('连接中') || props.status.includes('重连')) return '#ff9800';
    return '#f44336';
  }};
  
  ${props => props.isConnected && `
    animation: pulse 2s infinite;
    
    @keyframes pulse {
      0%, 100% {
        transform: scale(1);
        opacity: 1;
      }
      50% {
        transform: scale(1.2);
        opacity: 0.7;
      }
    }
  `}
`;

const HeaderRight = styled.div`
  display: flex;
  align-items: center;
  gap: 16px;

  @media (max-width: 768px) {
    flex-direction: column;
    gap: 8px;
  }
`;

const UserInfo = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;

  @media (max-width: 768px) {
    align-items: center;
  }
`;

const UserName = styled.span`
  font-weight: 600;
  font-size: 15px;
`;

const UserLabel = styled.span`
  font-size: 12px;
  opacity: 0.8;
`;

const DisconnectButton = styled.button`
  padding: 8px 16px;
  background: rgba(255, 255, 255, 0.2);
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.3s ease;
  backdrop-filter: blur(10px);

  &:hover {
    background: rgba(255, 255, 255, 0.3);
    transform: translateY(-1px);
  }

  &:active {
    transform: translateY(0);
  }

  @media (max-width: 768px) {
    padding: 6px 12px;
    font-size: 12px;
  }
`;

const TechBadge = styled.div`
  font-size: 10px;
  opacity: 0.7;
  background: rgba(255, 255, 255, 0.1);
  padding: 2px 6px;
  border-radius: 4px;
  margin-top: 2px;
`;

const ChatHeader: React.FC<ChatHeaderProps> = observer(({ 
  user, 
  connectionStatus, 
  isConnected, 
  onDisconnect 
}) => {
  return (
    <HeaderContainer>
      <HeaderLeft>
        <Title>
          <span>🚀</span>
          WebSocket 聊天室
        </Title>
        <ConnectionStatus>
          <StatusIndicator 
            isConnected={isConnected} 
            status={connectionStatus}
          />
          {connectionStatus}
        </ConnectionStatus>
      </HeaderLeft>

      <HeaderRight>
        <UserInfo>
          <UserName>{user}</UserName>
          <UserLabel>当前用户</UserLabel>
          <TechBadge>MobX + TypeScript</TechBadge>
        </UserInfo>
        
        <DisconnectButton onClick={onDisconnect}>
          断开连接
        </DisconnectButton>
      </HeaderRight>
    </HeaderContainer>
  );
});

ChatHeader.displayName = 'ChatHeader';

export default ChatHeader;

// Knowledge/frontend/packages/WebSocket/webSocket-vue-demo/src/components/ChatHeader.vue
<template>
  <header class="chat-header">
    <div class="header-left">
      <div class="room-info">
        <h2 class="room-title">WebSocket 聊天室</h2>
        <div class="connection-status" :class="statusClass">
          <div class="status-indicator"></div>
          <span class="status-text">{{ connectionStatus }}</span>
        </div>
      </div>
    </div>
    
    <div class="header-right">
      <div class="user-info">
        <div class="user-avatar">
          {{ userInitial }}
        </div>
        <div class="user-details">
          <span class="username">{{ user }}</span>
          <span class="user-status">在线</span>
        </div>
      </div>
      
      <button 
        class="disconnect-button"
        @click="$emit('disconnect')"
        title="退出聊天室"
      >
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor">
          <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
          <polyline points="16,17 21,12 16,7" />
          <line x1="21" y1="12" x2="9" y2="12" />
        </svg>
      </button>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ChatHeaderProps } from '@/types'

// Props
const props = defineProps<ChatHeaderProps>()

// Emits
defineEmits<{
  disconnect: []
}>()

// 计算属性
const userInitial = computed<string>(() => {
  return props.user.charAt(0).toUpperCase()
})

const statusClass = computed<string>(() => {
  return props.isConnected ? 'connected' : 'disconnected'
})
</script>

<style scoped>
.chat-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 1.5rem;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.header-left {
  flex: 1;
}

.room-info {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.room-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin: 0;
}

.connection-status {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
  opacity: 0.9;
}

.status-indicator {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  animation: pulse 2s infinite;
}

.connection-status.connected .status-indicator {
  background: #10b981;
}

.connection-status.disconnected .status-indicator {
  background: #ef4444;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.user-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  font-size: 1.125rem;
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.user-details {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}

.username {
  font-weight: 600;
  font-size: 0.875rem;
}

.user-status {
  font-size: 0.75rem;
  opacity: 0.8;
}

.disconnect-button {
  padding: 0.5rem;
  background: rgba(255, 255, 255, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: 8px;
  color: white;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
}

.disconnect-button:hover {
  background: rgba(255, 255, 255, 0.2);
  transform: translateY(-1px);
}

@keyframes pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.5;
  }
}

@media (max-width: 768px) {
  .chat-header {
    padding: 0.75rem 1rem;
  }
  
  .room-title {
    font-size: 1.125rem;
  }
  
  .user-details {
    display: none;
  }
  
  .user-avatar {
    width: 32px;
    height: 32px;
    font-size: 1rem;
  }
}
</style>
